### PR TITLE
feat: add aa-bundler Rust

### PR DESCRIPTION
**Pull request by Vid201**

### CODE REVIEW

**Comment by drortirosh** [comment]
please note that your bundler test doesn't run. it fails on:
./runall.sh: line 35: ../launchers/aa-bundler-rust-launcher.sh: Permission denied

Try to run it locally, by doing "./runall"

**Comment by drortirosh** [comment]
I did
```
git clone https://github.com/Vid201/bundler-test-executor.git rust-bundler
```
and executed "./runall.sh", and it failed the same.
After:
```
chmod a+rx launchers/aa-bundler-rust/aa-bundler-rust-launcher.sh
```

it starts the script, but fails to download the docker image.

Before pushing an update, make sure to try the above sequence (on a machine without special permission to your docker repo..)

**Comment by Vid201** [comment]
> I did
> 
> ```
> git clone https://github.com/Vid201/bundler-test-executor.git rust-bundler
> ```
> 
> and executed "./runall.sh", and it failed the same. After:
> 
> ```
> chmod a+rx launchers/aa-bundler-rust/aa-bundler-rust-launcher.sh
> ```
> 
> it starts the script, but fails to download the docker image.
> 
> Before pushing an update, make sure to try the above sequence (on a machine without special permission to your docker repo..)

Thanks for checking @drortirosh . Yes, it was my bad, sorry for that. I think it should be fine now.

**Comment by drortirosh** [comment]
@Vid201 , the PR is merged, but now i see it fails many tests. Please check and submit a new PR.

**Pull request merged**
