### PR TITLE
Skandha<->Silius p2p tests

### PR DESCRIPTION
**Pull request by Vid201**
I created a new PR since there were some conflicts on the previous. Basic P2P tests passes now.

@drortirosh

### CODE REVIEW

**Review by rondales — APPROVED** [review]

**Comment by drortirosh** [comment]
can you please rebase this pr? the diff shows a lot of things that are not there..

**Comment by Vid201** [comment]
> can you please rebase this pr? the diff shows a lot of things that are not there..

rebased

**Comment by drortirosh** [comment]
what I don't understand, is why your PR modifies the launcher scripts? they are unrelated.

**Comment by Vid201** [comment]
> what I don't understand, is why your PR modifies the launcher scripts? they are unrelated.

You mean `runall.sh` ?

The problem was that now tests for single bundler are always automatically started when you want to run only p2p tests (because `pytest run test` will always start single bundler tests https://github.com/eth-infinitism/bundler-spec-tests/commit/2b396495ad4bb526c0a0ad39d3795068a142cd2d)

**Comment by Vid201** [comment]
@drortirosh I clean this PR. Suggest merging PR #54 first.

**Pull request merged**
